name: CMake

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install -y libgtkmm-3.0-dev libsystemd-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WSysMon
        path: ${{github.workspace}}/build/WSysMon
